import Head from "next/head";

export default function Clint() {
  return (
    <>
      <Head>
        <title>Clint</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
       <h1>hi sss</h1>
      </div>
    </>
  );
}

