import Head from "next/head";
import MainLayout from "@/components/common/layouts/MainLayout";

;

export default function Categoris() {
  return (
    <>
      <Head>
        <title>Categoris</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div></div>
    </>
  );
}
Categoris.getLayout = (pageProps) => (
    <MainLayout>
      <Categoris {...pageProps} />
    </MainLayout>
  );
  