import Head from "next/head";
import styles from "@/styles/Home.module.css";
import MainLayout from "@/components/Main";
import CustomersList from "@/components/page/customers/Customers";

export default function Customers() {
  return (
    <>
      <Head>
        <title>Cutomers List</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <CustomersList />
      </div>
    </>
  );
}

Customers.getLayout = (pageProps) => (
    <MainLayout>
      <Customers {...pageProps} />
    </MainLayout>
)