import Head from "next/head";
import MainLayout from "@/components/common/layouts/MainLayout";
import useCurrentUser from "@/hooks/useCurrentUser";
import useFetchApiItems from "@/hooks/useFetchApiItems";

export default function Dashboard() {
  const [user, handleCategories, handleType] = useCurrentUser();
  const [categories, isLoading] = useFetchApiItems(
    `/categories?filters[restaurant][documentId][$eqi]=${user?.restaurantId}`
  );

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <button
          onClick={() => {
            handleCategories(user.restaurantId);
          }}
        >
          Categories
        </button>
        <button
          onClick={() => {
            handleType(categories);
          }}
        >
          type
        </button>
      </div>
    </>
  );
}

Dashboard.getLayout = (pageProps) => (
  <MainLayout>
    <Dashboard {...pageProps} />
  </MainLayout>
);
