import Head from "next/head";
import TextField from '@mui/material/TextField';
import MainLayout from "@/components/common/layouts/MainLayout";

export default function NewFood() {
  return (
    <>
      <Head>
        <title>New Food</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <form>
        <TextField id="outlined-basic" label="Name" type="text" variant="outlined" />
        <TextField id="outlined-basic" label="Outlined" variant="outlined" />
            <button type="submit">Click</button>
        </form>
      </div>
    </>
  );
}

NewFood.getLayout = (pageProps) => (
  <MainLayout>
    <NewFood {...pageProps} />
  </MainLayout>
);
