import Head from "next/head";
import MainLayout from "@/components/common/layouts/MainLayout";
import FoodForm from "@/components/pages/foods/FoodForm";

export default function NewFood() {
  return (
    <>
      <Head>
        <title>New Food</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <FoodForm title={"Create new food"} btnText={"Create new Food"}/>
      </div>
    </>
  );
}

NewFood.getLayout = (pageProps) => (
  <MainLayout>
    <NewFood {...pageProps} />
  </MainLayout>
);
