export const orderListData = [
  {
    id: "765231",
    date: "26 March 2020, 12:42 AM",
    userName: "Mikasa Ackerman",
    location: "Corner Street 5th London",
    amount: 164.52,
    status: "New Order",
    items: [
      {
        id: "1",
        img: "/turtburchak.png",
        name: "MAIN COURSE",
        text: "Watermelon juice with ice",
        x: 5,
        cost: 5.79,
      },
    ],
    deliveryBy: {
      id: "412455",
      name: "Kevin Hobs Jr.",
      phone: "+12 345 5662 66",
      time: "12.53",
      img: "/turtburchak.png",
    },
  },
  {
    id: "135231",
    date: "26 March 2020, 12:42 AM",
    userName: "Eren Ackerman",
    location: "Corner Street 5th London",
    amount: 164.52,
    status: "On Delivery",
    items: [
      {
        id: "2",
        img: "/turtburchak.png",
        name: "MAIN COURSE",
        text: "Watermelon juice with ice",
        x: 4,
        cost: 20.1,
      },
    ],
    deliveryBy: {
      id: "412455",
      name: "Kevin Hobs Jr.",
      phone: "+12 345 5662 66",
      time: "12.53",
      img: "/turtburchak.png",
    },
  },
  {
    id: "325231",
    date: "26 March 2020, 12:42 AM",
    userName: "Mikasa Ackerman",
    location: "Corner Street 5th London",
    amount: 164.52,
    status: "Delivered",
    items: [
      {
        id: "3",
        img: "/turtburchak.png",
        name: "MAIN COURSE",
        text: "Watermelon juice with ice",
        x: 2,
        cost: 18,
      },
    ],
    deliveryBy: {
      id: "412455",
      name: "Kevin Hobs Jr.",
      phone: "+12 345 5662 66",
      time: "12.53",
      img: "/turtburchak.png",
    },
  },
  {
    id: "555231",
    date: "26 March 2020, 12:42 AM",
    userName: "Mikasa Ackerman",
    location: "Corner Street 5th London",
    amount: 164.52,
    status: "New Order",
    items: [
      {
        id: "4",
        img: "/turtburchak.png",
        name: "MAIN COURSE",
        text: "Watermelon juice with ice",
        x: 1,
        cost: 5,
      },
    ],
    deliveryBy: {
      id: "412455",
      name: "Kevin Hobs Jr.",
      phone: "+12 345 5662 66",
      time: "12.53",
      img: "/turtburchak.png",
    },
  },
  {
    id: "523231",
    date: "26 March 2020, 12:42 AM",
    userName: "Mikasa Ackerman",
    location: "Corner Street 5th London",
    amount: 164.52,
    status: "On Delivery",
    items: [
      {
        id: "5",
        img: "/turtburchak.png",
        name: "MAIN COURSE",
        text: "Watermelon juice with ice",
        x: 9,
        cost: 20,
      },
    ],
    deliveryBy: {
      id: "412455",
      name: "Kevin Hobs Jr.",
      phone: "+12 345 5662 66",
      time: "12.53",
      img: "/turtburchak.png",
    },
  },
  {
    id: "558831",
    date: "26 March 2020, 12:42 AM",
    userName: "Mikasa Ackerman",
    location: "Corner Street 5th London",
    amount: 164.52,
    status: "Delivered",
    items: [
      {
        id: "6",
        img: "/turtburchak.png",
        name: "MAIN COURSE",
        text: "Watermelon juice with ice",
        x: 4,
        cost: 5.79,
      },
    ],
    deliveryBy: {
      id: "412455",
      name: "Kevin Hobs Jr.",
      phone: "+12 345 5662 66",
      time: "12.53",
      img: "/turtburchak.png",
    },
  },
];
export const customerData = [
  {
    id: "765231",
    date: "26 March 2020, 12:42 AM",
    userName: "Mikasa Ackerman",
    location: "Corner Street 5th London",
    amount: 164.52,
    lastAmount: 98,
    item:[{
      id:'1',
      img:'/burchak.png',
      food:'Meidum Spicy Spagethi Italiano',
      name:'SPAGETHI',
      cost:'12.56',
    }]
  },
  {
    id: "135231",
    date: "26 March 2020, 12:42 AM",
    userName: "Mikasa Ackerman",
    location: "Corner Street 5th London",
    amount: 164.52,
    lastAmount: 98,
    item:[{
      id:'2',
      img:'/burchak.png',
      food:'Meidum Spicy Spagethi Italiano',
      name:'SPAGETHI',
      cost:'12.56',
    }]
  },
  {
    id: "325231",
    date: "26 March 2020, 12:42 AM",
    userName: "Mikasa Ackerman",
    location: "Corner Street 5th London",
    amount: 164.52,
    lastAmount: 98,
    item:[{
      id:'3',
      img:'/burchak.png',
      food:'Meidum Spicy Spagethi Italiano',
      name:'SPAGETHI',
      cost:'12.56',
    }]
  },
  {
    id: "555231",
    date: "26 March 2020, 12:42 AM",
    userName: "Mikasa Ackerman",
    location: "Corner Street 5th London",
    amount: 164.52,
    lastAmount: 98,
    item:[{
      id:'4',
      img:'/burchak.png',
      food:'Meidum Spicy Spagethi Italiano',
      name:'SPAGETHI',
      cost:'12.56',
    }]
  },
  {
    id: "523231",
    date: "26 March 2020, 12:42 AM",
    userName: "Mikasa Ackerman",
    location: "Corner Street 5th London",
    amount: 164.52,
    lastAmount: 98,
    item:[{
      id:'5',
      img:'/burchak.png',
      food:'Meidum Spicy Spagethi Italiano',
      name:'SPAGETHI',
      cost:'12.56',
    }]
  },
  {
    id: "558831",
    date: "26 March 2020, 12:42 AM",
    userName: "Mikasa Ackerman",
    location: "Corner Street 5th London",
    amount: 164.52,
    lastAmount: 98,
    item:[{
      id:'6',
      img:'/burchak.png',
      food:'Meidum Spicy Spagethi Italiano',
      name:'SPAGETHI',
      cost:'12.56',
    }]
  },
];

export const foodData = [
  {
    id: '1',
    img: '',
    name: 'Spicy Mozarella with Barbeque',
    title: 'food',
    context: 'noodle',
  },
  {
      id: '2',
      img: '',
      name: 'Spicy Mozarella with Barbeque',
      title: 'food',
      context: 'noodle',
    },
    {
      id: '3',
      img: '',
      name: 'Spicy Mozarella with Barbeque',
      title: 'food',
      context: 'noodle',
    },
    {
      id: '4',
      img: '',
      name: 'Spicy Mozarella with Barbeque',
      title: 'food',
      context: 'noodle',
    },
    {
      id: '5',
      img: '',
      name: 'Spicy Mozarella with Barbeque',
      title: 'food',
      context: 'noodle',
    },
];
