import { Box } from "@mui/material";
import Head from "next/head";
import { useUsersWithRestaurants } from "@/hooks/useUsersWithRestaurants";
import { useRouter } from "next/router";

export default function Clint() {
  const { users, loading } = useUsersWithRestaurants();

  return (
    <>
      <Head>
        <title>Clint</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box
        sx={{
          maxWidth: "1440px",
          width: "100%",
          margin: "0 auto",
          display: "flex",
          gap: "16px",
          flexWrap: "wrap",
        }}
      >
        {users
          ?.filter((item) => item.restaurant)
          .map((item) => (
            <ResCard key={item.id} items={item} />
          ))}
      </Box>
    </>
  );
}
function ResCard({ items }) {
  const handleClick = () => {
    router.push(`/client/res/[${items?.restaurant?.name}]`);
  };
  const router = useRouter();
  return (
    <Box
      sx={{
        maxWidth: "340px",
        width: "100%",
        overflow: "hidden",
        opacity: "100%",
        "&:hover": {
          opacity: "70%",
          transition: ".3s",
        },
      }}
      onClick={handleClick}
    >
      <Box sx={{ width: "100%", height: "180px" }}>
        <img
          src="/fast.png"
          alt={items?.restaurant?.name || "User"}
          style={{
            width: "100%",
            height: "100%",
            objectFit: "cover",
            borderRadius: "16px",
          }}
        />
      </Box>

      <Box sx={{ padding: "16px" }}>
        <Box
          sx={{
            display: "flex",
            justifyContent: "space-between",
            alignItems: "center",
          }}
        >
          <h4 style={{ margin: 0 }}>
            {items?.restaurant?.name || "Topilmadi"}
          </h4>
          <p style={{ margin: 0 }}>⭐ 5</p>
        </Box>
      </Box>
    </Box>
  );
}
