import MainLayout from "@/components/common/layouts/MainLayout";
import Head from "next/head";

export default function Foods() {
    return (
      <>
        <Head>
          <title>Foods</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <div>
        <p>Good bye noob</p>
        </div>
      </>
    );
  }
  
  Foods.getLayout = (pageProps) => (
    <MainLayout>
      <Foods {...pageProps} />
    </MainLayout>
  );
  